#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BACKEND_PATTERN="applications/backend"
FRONTEND_PATTERN="applications/frontend"

if git diff --cached --name-only | grep --quiet "$BACKEND_PATTERN" && git diff --cached --name-only | grep --quiet "$FRONTEND_PATTERN"; then
  echo "️➡️ Linting backend & frontend applications"
  pnpm lint
  pnpm typecheck

elif git diff --cached --name-only | grep --quiet "$BACKEND_PATTERN"; then
  echo "➡️ Linting backend applications"
  pnpm lint:backend

elif git diff --cached --name-only | grep --quiet "$FRONTEND_PATTERN"; then
  echo "➡️ Linting frontend applications"
  pnpm lint:frontend
  pnpm typecheck

else
  echo "✅ No applications to lint"
fi
